export const MEASURE_ID = '__measures__';
export const TOTAL_ID = '__total__';

export const KEY_SEPARATOR = '-/-';

// ACTIONS

export const SET_FIELDS = 'PIVOTGRID_SET_FIELDS';
export const SET_DATAFIELDS = 'PIVOTGRID_SET_DATAFIELDS';
export const SET_CONFIG_PROPERTY = 'PIVOTGRID_SET_CONFIG_PROPERTY';
export const TOGGLE_DATAFIELD = 'PIVOTGRID_TOGGLE_DATAFIELD';
export const MOVE_FIELD = 'PIVOTGRID_MOVE_FIELD';

export const PUSH_DATA = 'PIVOTGRID_PUSH_DATA';
export const SET_DATA = 'PIVOTGRID_SET_DATA';

export const CHANGE_SORT_ORDER = 'PIVOTGRID_CHANGE_SORT_ORDER';

export const ADD_FILTER = 'PIVOTGRID_ADD_FILTER';
export const DELETE_FILTER = 'PIVOTGRID_DELETE_FILTER';

export const UPDATE_CELL_SIZE = 'PIVOTGRID_UPDATE_CELL_SIZE';

export const ZOOM_IN = 'PIVOTGRID_ZOOM_IN';
export const ZOOM_OUT = 'PIVOTGRID_ZOOM_OUT';
