export const MEASURE_ID = "__measures__";
export const TOTAL_ID = "__total__";

export const ALL = "__all__";

export const KEY_SEPARATOR = "-/-";
export const AXIS_SEPARATOR = "-//-";

// ACTIONS

export const SET_DIMENSIONS = "PIVOTGRID_SET_DIMENSIONS";
export const SET_MEASURES = "PIVOTGRID_SET_MEASURES";
export const SET_CONFIG_PROPERTY = "PIVOTGRID_SET_CONFIG_PROPERTY";
export const TOGGLE_MEASURE = "PIVOTGRID_TOGGLE_MEASURE";
export const MOVE_DIMENSION = "PIVOTGRID_MOVE_DIMENSION";
export const SET_AXIS = "PIVOTGRID_SET_AXIS";

export const PUSH_DATA = "PIVOTGRID_PUSH_DATA";
export const SET_DATA = "PIVOTGRID_SET_DATA";

export const CHANGE_SORT_ORDER = "PIVOTGRID_CHANGE_SORT_ORDER";

export const ADD_FILTER = "PIVOTGRID_ADD_FILTER";
export const DELETE_FILTER = "PIVOTGRID_DELETE_FILTER";

export const UPDATE_CELL_SIZE = "PIVOTGRID_UPDATE_CELL_SIZE";

export const ZOOM_IN = "PIVOTGRID_ZOOM_IN";
export const ZOOM_OUT = "PIVOTGRID_ZOOM_OUT";
